# Generated by Codex on 2026-06-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0001_initial'),
        ('ui_automation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='app_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_automation.appdevice', verbose_name='目标设备'),
        ),
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='app_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_automation.apppackage', verbose_name='目标应用包'),
        ),
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='ui_flow_snapshot',
            field=models.JSONField(blank=True, default=list, verbose_name='移动端 UI Flow 快照'),
        ),
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='saved_app_test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_ai_execution_records', to='app_automation.apptestcase', verbose_name='已保存 APP 测试用例'),
        ),
        migrations.AlterField(
            model_name='aiexecutionrecord',
            name='execution_mode',
            field=models.CharField(choices=[('text', '文本模式'), ('mobile', '移动端自主模式')], default='text', max_length=20, verbose_name='执行模式'),
        ),
    ]
