# Generated by Django 4.2.7 on 2026-06-08 12:25

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationStats',
            fields=[
            ],
            options={
                'verbose_name': '注册统计',
                'verbose_name_plural': '注册统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='事件名称')),
                ('event_type', models.CharField(default='custom', max_length=32, verbose_name='事件类型')),
                ('module', models.CharField(blank=True, default='', max_length=64, verbose_name='所属模块')),
                ('page_path', models.CharField(blank=True, default='', max_length=255, verbose_name='页面路径')),
                ('route_name', models.CharField(blank=True, default='', max_length=100, verbose_name='路由名称')),
                ('referrer_path', models.CharField(blank=True, default='', max_length=255, verbose_name='来源页面')),
                ('target_path', models.CharField(blank=True, default='', max_length=255, verbose_name='目标页面')),
                ('success', models.BooleanField(blank=True, null=True, verbose_name='是否成功')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='耗时毫秒')),
                ('session_id', models.CharField(blank=True, default='', max_length=64, verbose_name='会话ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='客户端IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '埋点事件',
                'verbose_name_plural': '埋点事件',
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analytics_e_created_c06122_idx'), models.Index(fields=['event_name', '-created_at'], name='analytics_e_event_n_b5243a_idx'), models.Index(fields=['module', 'event_name', '-created_at'], name='analytics_e_module_814571_idx'), models.Index(fields=['session_id', '-created_at'], name='analytics_e_session_c88a44_idx'), models.Index(fields=['user', '-created_at'], name='analytics_e_user_id_e1a457_idx')],
            },
        ),
    ]
